version: "3.8"

services:
  reservas:
    build: ./reservas
    container_name: reservas
    env_file:
      - ./reservas/infrastructure/config/database.env
      - ./reservas/infrastructure/config/kafka.env
    depends_on:
      - kafka
    networks:
      - travel-hub-net

  billing:
    build: ./billing
    container_name: billing
    env_file:
      - ./billing/infrastructure/config/database.env
      - ./billing/infrastructure/config/kafka.env
    depends_on:
      - kafka
    networks:
      - travel-hub-net

  payments:
    build: ./payments
    container_name: payments
    env_file:
      - ./payments/infrastructure/config/database.env
      - ./payments/infrastructure/config/kafka.env
    depends_on:
      - kafka
    networks:
      - travel-hub-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - travel-hub-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - travel-hub-net

  nginx:
    image: nginx:1.25
    container_name: api-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - reservas
      - billing
      - payments
    networks:
      - travel-hub-net

  monitor:
    build: ./monitor
    container_name: monitor
    # Este componente debe implementarse para hacer healthchecks a los servicios cada 10s
    ports:
      - "8081:8080"
    networks:
      - travel-hub-net

networks:
  travel-hub-net:
    driver: bridge